server:
  servlet:
    contextPath: /api
spring:
  rabbitmq:
    exchange: amq.direct
    studentqueue: student-queue
    studentrouting: student-routing-key
student:
  file:
    path: C:\Users\gabrielamaciac\Documents\GitHub\student\new
    successful: C:\Users\gabrielamaciac\Documents\GitHub\student\successful
    archived: C:\Users\gabrielamaciac\Documents\GitHub\student\archived