server:
  servlet:
    contextPath: /api
spring:
  rabbitmq:
    exchange: amq.direct
    studentqueue: student-queue
    validationqueue: validation-queue
    studentrouting: student-routing-key
student:
  file:
    path: C:\Users\gabrielamaciac\Documents\GitHub\student
